'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("XMLIO.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;textures&gt;
        '''	&lt;texture&gt;
        '''		&lt;id&gt;0&lt;/id&gt;
        '''		&lt;name&gt;Dirt&lt;/name&gt;
        '''		&lt;path&gt;\Textures\dirt_texture.jpg&lt;/path&gt;
        '''		&lt;noColumns&gt;1&lt;/noColumns&gt;
        '''		&lt;noRows&gt;1&lt;/noRows&gt;
        '''	&lt;/texture&gt;
        '''	&lt;texture&gt;
        '''		&lt;id&gt;1&lt;/id&gt;
        '''		&lt;name&gt;Grass&lt;/name&gt;
        '''		&lt;path&gt;\Textures\grass_texture.jpg&lt;/path&gt;
        '''		&lt;noColumns&gt;1&lt;/noColumns&gt;
        '''		&lt;noRows&gt;1&lt;/noRows&gt;
        '''	&lt;/texture&gt;
        '''	&lt;texture&gt;
        '''		&lt;id&gt;2&lt;/id&gt;
        '''		&lt;name&gt;Ground&lt;/name&gt;
        '''		&lt;path&gt;\Textures\ground_texture.jpg&lt;/path&gt;
        '''		&lt;noColumns&gt;1&lt;/noColumns&gt;
        '''		&lt;noRows&gt;1&lt;/noRows&gt;
        '''	&lt;/text [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GeneralTexturesXML() As String
            Get
                Return ResourceManager.GetString("GeneralTexturesXML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''  &lt;xs:element name=&quot;textures&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:sequence&gt;
        '''        &lt;xs:element maxOccurs=&quot;unbounded&quot; name=&quot;texture&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element name=&quot;id&quot; type=&quot;xs:integer&quot; /&gt;
        '''              &lt;xs:element name=&quot;name&quot; type=&quot;xs:string&quot; /&gt;
        '''              &lt;xs:element name=&quot;path&quot; type= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GeneralTexturesXSD() As String
            Get
                Return ResourceManager.GetString("GeneralTexturesXSD", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
